# Generated by Django 4.1.2 on 2022-10-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='headline_role',
        ),
    ]
