# Generated by Django 4.1.2 on 2022-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_image_recruiterprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
