# Generated by Django 4.1.2 on 2022-10-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_recruiterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('application_type', models.CharField(blank=True, choices=[('email', 'Email'), ('link', 'Link')], max_length=15, null=True)),
                ('application_type_value', models.CharField(blank=True, choices=[('email', 'Email'), ('link', 'Link')], max_length=15, null=True)),
                ('job_type', models.CharField(choices=[('freelance', 'Freelance'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=100)),
                ('job_location', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], max_length=100)),
                ('is_available', models.BooleanField(default=False)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('qualifications', models.JSONField(blank=True, null=True)),
                ('compensation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='available_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
    ]
