# Generated by Django 4.1.2 on 2022-10-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_roles_company_available_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='available_roles',
        ),
        migrations.AddField(
            model_name='roles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
