# Generated by Django 4.1.2 on 2022-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_roles_application_type_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='application_type_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
