# Generated by Django 4.1.2 on 2022-10-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Tells if this role is open / available'),
        ),
    ]
