# Generated by Django 4.1.2 on 2022-10-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_roles_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
