# Generated by Django 4.1.2 on 2022-10-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_company_is_completed_company_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
