# Generated by Django 4.1.2 on 2022-10-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_alter_recruiterprofile_user'),
        ('accounts', '0017_alter_company_contact_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.recruiterprofile'),
        ),
    ]
