# Generated by Django 4.1.2 on 2022-10-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
