# Generated by Django 4.1.2 on 2022-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_image_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile-pictures/flower.jpeg', null=True, upload_to='profile-pictures'),
        ),
    ]
