# Generated by Django 4.1.2 on 2023-02-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_recruiterprofile_verification_token'),
        ('accounts', '0036_alter_company_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='recruiter.recruiterprofile'),
        ),
    ]
