# Generated by Django 4.1.2 on 2023-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_offer_offered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accepted',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
