# Generated by Django 4.1.2 on 2023-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_offer_accepted_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected'), ('pend', 'Pending')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='roles',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Tells if this role is open / available'),
        ),
    ]
