# Generated by Django 4.1.2 on 2022-10-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('headline_role', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('expectation', models.JSONField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('freelance', 'Freelance'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=100, null=True)),
                ('can_relocate', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('available_for_offer', models.BooleanField(default=True)),
                ('socials', models.JSONField(blank=True, null=True)),
                ('up_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, help_text='example: backend developer, HTML, Rust, Python', to='techie.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
