# Generated by Django 4.1.2 on 2022-10-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company'),
        ('techie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='companies',
            field=models.ManyToManyField(help_text='Companies techies has worked with', to='accounts.company'),
        ),
    ]
