# Generated by Django 4.1.2 on 2022-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0002_techieprofile_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='job_location',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], max_length=100, null=True),
        ),
    ]
