# Generated by Django 4.1.2 on 2022-10-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techie', '0003_techieprofile_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techieprofile',
            name='expectation',
        ),
        migrations.RemoveField(
            model_name='techieprofile',
            name='up_votes',
        ),
        migrations.AlterField(
            model_name='techieprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('techie_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techie.techieprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expection_value', models.CharField(blank=True, help_text='This receives $800 - $3000, Flexible PTO', max_length=300, null=True)),
                ('techie_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techie.techieprofile')),
            ],
        ),
    ]
