# Generated by Django 4.1.2 on 2022-10-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0004_remove_techieprofile_expectation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectation',
            old_name='expection_value',
            new_name='expectation_value',
        ),
    ]
