# Generated by Django 4.1.2 on 2022-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0005_rename_expection_value_expectation_expectation_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'Responsibilities'},
        ),
        migrations.AddField(
            model_name='techieprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='expectation_value',
            field=models.CharField(blank=True, help_text='What a techie should expect from any interested company.Example: $800 - $3000/month, Flexible PTO', max_length=300, null=True),
        ),
    ]
