# Generated by Django 4.1.2 on 2022-10-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0006_alter_responsibility_options_techieprofile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
