# Generated by Django 4.1.2 on 2022-10-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_upvote_company_up_votes'),
        ('techie', '0007_techieprofile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='up_votes',
            field=models.ManyToManyField(blank=True, to='accounts.upvote'),
        ),
    ]
