# Generated by Django 4.1.2 on 2022-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0008_techieprofile_up_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
