# Generated by Django 4.1.2 on 2022-10-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0010_remove_techieprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
