# Generated by Django 4.1.2 on 2022-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0012_remove_techieprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='techieprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='techieprofile',
            name='headline_role',
            field=models.CharField(blank=True, default='Techie', max_length=100, null=True),
        ),
    ]
