# Generated by Django 4.1.2 on 2022-12-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techie', '0013_techieprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techieprofile',
            name='image',
        ),
    ]
