# Generated by Django 4.1.2 on 2022-10-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='profile',
            new_name='user',
        ),
    ]
