# Generated by Django 4.1.2 on 2022-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_rename_profile_recruiterprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='headline_role',
            field=models.CharField(default='Recruiter', max_length=100, null=True),
        ),
    ]
