# Generated by Django 4.1.2 on 2022-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_recruiterprofile_headline_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='my_job_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
