# Generated by Django 4.1.2 on 2022-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_recruiterprofile_my_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
