# Generated by Django 4.1.2 on 2022-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_recruiterprofile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
