# Generated by Django 4.1.2 on 2022-10-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_rename_company_recruiterprofile_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='country',
            new_name='location',
        ),
    ]
