# Generated by Django 4.1.2 on 2022-10-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_rename_country_recruiterprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='location',
            new_name='country',
        ),
    ]
