# Generated by Django 4.1.2 on 2022-10-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_rename_location_recruiterprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='If recruiter has entered the minimum requirements'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='my_job_location',
            field=models.CharField(blank=True, default='', help_text='Where this Recruiter works', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='owner_user_id',
            field=models.CharField(blank=True, default='', help_text='This field holds the ID of the USER that has this Recruiter profile, in case he switches to a Techie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text="If recruiter has been verified by our platform's verification methods"),
        ),
    ]
