# Generated by Django 4.1.2 on 2022-10-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_alter_recruiterprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='image',
        ),
    ]
