# Generated by Django 4.1.2 on 2022-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_remove_recruiterprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
