# Generated by Django 4.1.2 on 2022-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0016_remove_recruiterprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
