from django.contrib.auth.hashers import check_password, make_password
from django.db.models import Q
from django.shortcuts import HttpResponse
import secrets
from django.contrib.auth import authenticate
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_201_CREATED
from rest_framework_simplejwt.tokens import AccessToken, RefreshToken
from accounts.models import UpVote, Company, ActivationToken
from recruiter.models import RecruiterProfile
from recruiter.serializers import RecruiterProfileSerializer
from .serializers import UserSerializer
from .utils import validate_email, validate_image
from techie.models import User, TechieProfile
from techie.serializers import TechieProfileSerializer, CompanySerializer
from rest_framework import status


# Create your views here.


def index(request):
    return HttpResponse("WELCOME TO TECHIES.JOBS DEVELOPMENT AREA")

# Create your views here.


class ManualSignUpView(APIView):
    permission_classes = []

    def post(self, request):
        try:
            username, email = request.data.get("username", None), request.data.get("email", None)
            password = request.data.get("password", None)
            password_confirm = request.data.get("password_confirm", None)
            activation_token = request.data.get("activation_token", None)
            message = ""
            # terms_and_conditions = request.data.get("terms_and_conditions", None)

            if email is not None:
                if validate_email(email) is False:
                    return Response({"detail": "Invalid email format"}, status=HTTP_400_BAD_REQUEST)
            else:
                return Response({"detail": "Email field is required"}, status=HTTP_400_BAD_REQUEST)

            if username is None:
                return Response({"detail": "Username field is required"}, status=HTTP_400_BAD_REQUEST)

            if username.split(' ') is True:
                return Response({"detail": "Username should not contain white spaces"}, status=HTTP_400_BAD_REQUEST)

            if password is None:
                return Response({"detail": "Password field is required"}, status=HTTP_400_BAD_REQUEST)

            if password_confirm is None:
                return Response({"detail": "Confirm Password field is required"}, status=HTTP_400_BAD_REQUEST)

            # if terms_and_conditions is None:
            #     return Response({"detail": "User needs to accept our terms and conditions"},
            #                     status=HTTP_400_BAD_REQUEST)

            if password != password_confirm:
                return Response({"detail": "Passwords does not match"}, status=HTTP_400_BAD_REQUEST)

            user = User.objects.create_user(username=username, email=email, terms_and_conditions=True,
                                            signup_type="manual", user_role='techie', password=password)
            techie_instance = TechieProfile.objects.create(user=user, slug=secrets.token_urlsafe(15),
                                                           owner_user_id=user.id)

            # Activate user (For users that comes with an activation token generated by the Admin)
            if activation_token is not None:
                token_instance = ActivationToken.objects.filter(token=activation_token)
                if token_instance.exists():
                    techie_instance.verified = True
                    techie_instance.save()

                    token_instance = ActivationToken.objects.get(token=activation_token)
                    token_instance.delete()
                    message = "Verification was Successful."
                else:
                    message = "Verification was not Successful because an Invalid verification token was passed"
            if user is not None:
                # Send Welcome/Activation Mail To user's email here. !! NOTE: Mails should sent with Python Thread.


                # Keep things simple, log user in after signup (This is optional).
                return Response({"detail": f"User creation was successful and logged in. {message}",
                                 "data": {
                                     "access_token": f"{AccessToken.for_user(user)}",
                                     "refresh_token": f"{RefreshToken.for_user(user)}"
                                 }}, status=HTTP_200_OK)
            else:
                return Response({"detail": "User creation failed"}, status=HTTP_400_BAD_REQUEST)

        except (Exception,) as err:
            # Log error
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)


class ManualLoginView(APIView):
    permission_classes = []

    def post(self, request):
        try:
            username, email = request.data.get("username", None), request.data.get("email", None)
            password = request.data.get("password", None)

            user = None

            # if login_type is None:
            #     return Response({"detail": "Please specify a Login Type"}, status=HTTP_400_BAD_REQUEST)

            if email is not None:
                if validate_email(email) is False:
                    return Response({"detail": "Invalid email format"}, status=HTTP_400_BAD_REQUEST)
            else:
                return Response({"detail": "Email field is required"}, status=HTTP_400_BAD_REQUEST)

            if password is None:
                return Response({"detail": "Password field is required"}, status=HTTP_400_BAD_REQUEST)

            user = authenticate(request, email=email, password=password)
            # elif login_type == "social":
            # if username is None:
            #     username = f"techie-{secrets.token_urlsafe(5)}"
            # user = User.objects.get(email=email)

            if user is not None:
                user.login_type = "manual"
                user.save()
                # Check if user has completed his personal info.
                serialised = UserSerializer(user, many=False, context={"request": request}).data
                return Response({"detail": "User has been successfully Authenticated",
                                 "data": {
                                     "access_token": f"{AccessToken.for_user(user)}",
                                     "refresh_token": f"{RefreshToken.for_user(user)}",
                                     "user_details": serialised,
                                 }}, status=HTTP_200_OK)
            else:
                return Response({"detail": "Failed to Authenticate user"}, status=HTTP_400_BAD_REQUEST)

        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)

class GetUserByUserNameView(APIView):
    permission_classes = []

    def get(self, request, username=None):
        try:
            if username is None:
                return Response({"detail": f"Please pass in username"}, status=status.HTTP_400_BAD_REQUEST)

            user = User.objects.filter(username=username)
            if not user:
                return Response({"detail": f"No user with username '{username}'."}, status=status.HTTP_400_BAD_REQUEST)

            user = User.objects.get(username=username)

            serialized_data = None
            if user.user_role == "recruiter":
                recruiter_profile = RecruiterProfile.objects.get(user=user)
                serialized_data = RecruiterProfileSerializer(recruiter_profile, many=False,
                                                             context={"request": request}).data

            if user.user_role == "techie":
                techie_profile = TechieProfile.objects.get(user__username=username)
                serialized_data = TechieProfileSerializer(techie_profile, many=False, context={"request": request}).data

            return Response({"detail": f"Success", "data": serialized_data}, status=status.HTTP_200_OK)

        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=status.HTTP_400_BAD_REQUEST)


class UpVoteView(APIView):
    """
        Authenticated users calls this view (end-point) with an 'up_vote_instance_id' to up-vote an account / company.
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            up_vote_instance_id = request.data.get("up_vote_instance_id", None)
            company_id_or_slug = request.data.get("company_id_or_slug", None)

            if up_vote_instance_id is None and company_id_or_slug is None:
                return Response({"detail": "Supply a User's ID or Company's slug/ID to upvote."},
                                status=HTTP_400_BAD_REQUEST)

            # Check if the 'up_vote_instance_id' and 'company_id_or_slug' are supplied together.
            if up_vote_instance_id is not None and company_id_or_slug is not None:
                return Response({"detail": "You can only up-vote one instance at a time"}, status=HTTP_400_BAD_REQUEST)

            instance_to_vote_for = None
            # check if any user with 'up_vote_instance_id' exists

            if User.objects.filter(id=up_vote_instance_id).exists():
                # check if any user with 'up_vote_instance_id' exists
                user_instance_to_vote_for = User.objects.get(id=up_vote_instance_id)

                if user_instance_to_vote_for.id == request.user.id:
                    return Response({"detail": "You can't up-vote your account."}, status=HTTP_200_OK)

                if TechieProfile.objects.filter(user=user_instance_to_vote_for).exists():
                    techie_profile = TechieProfile.objects.get(user=user_instance_to_vote_for)

                    if techie_profile.up_votes.filter(user=user_instance_to_vote_for).exists():
                        return Response({"detail": "You have already up voted this profile"},
                                        status=status.HTTP_400_BAD_REQUEST)

                    up_vote = UpVote.objects.create(user=user_instance_to_vote_for)
                    techie_profile.up_votes.add(up_vote)
                    return Response({"detail": "Success"}, status=HTTP_200_OK)
            # End of upvote for user instance

            # Upvoting for company
            # print(not Company.objects.filter(slug=company_id_or_slug), "-------")
            if Company.objects.filter(slug=company_id_or_slug).exists():
                company = Company.objects.filter(slug=company_id_or_slug).first()
            elif Company.objects.filter(id=company_id_or_slug).exists():
                company = Company.objects.filter(id=company_id_or_slug).first()
            else:
                return Response({"detail": f"Invalid company slug/id field."}, status=HTTP_400_BAD_REQUEST)

            # up_vote = UpVote.objects.create(user=)
            if company.up_votes.filter(user=request.user).exists():
                return Response({"detail": "You have already up voted this Company"},
                                status=status.HTTP_400_BAD_REQUEST)
            up_vote = UpVote.objects.create(user=request.user)
            company.up_votes.add(up_vote)
            return Response({"detail": "Success"}, status=HTTP_200_OK)
            # End of up-voting for company

        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)


class CheckUserNameAvailability(APIView):
    permission_classes = []

    def get(self, request):
        try:
            query = request.GET.get("query", None)
            if User.objects.filter(username__iexact=query).exists():
                return Response({"detail": "Username is not available"}, status=status.HTTP_400_BAD_REQUEST)

            return Response({"detail": f"Username is available"}, status=status.HTTP_200_OK)
        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=status.HTTP_400_BAD_REQUEST)


class SwitchUserTypeView(APIView):
    permission_classes = [IsAuthenticated]
    """
        I need to rethink this switch idea. what if the current techie does not have a recruiter profile, will i still see the 
        switch button ? And is there a 'Become a Recruiter' button. what if i don't have a recruiter's account, what happens
        
        - Basic information should switch between profile.
    """

    def get(self, request):
        try:
            print(request.user.user_role)
            user = request.user
            if request.user.user_role == "techie":
                user.user_role = "recruiter"
                user.save()

                if RecruiterProfile.objects.filter(user=request.user).exists():
                    # Get his/her Techie's profile to collect switchable data like, socials,
                    techie_instance = TechieProfile.objects.get(user=user)
                    techie_socials = techie_instance.socials

                    recruiter_profile = RecruiterProfile.objects.get(user=request.user)
                    recruiter_socials = recruiter_profile.socials

                    # check: if techie and recruiter is not empty before performing 'socials' merging.
                    if techie_socials is not None and recruiter_socials is not None:
                        if "" in recruiter_socials:
                            del recruiter_socials[""]

                        for key, value in techie_socials.items():
                            # check: if 'key' e.g 'facebook' in "recruiter's" socials and if "key's" value is not empty.
                            if key in recruiter_socials and bool(recruiter_socials[key]) is False:
                                recruiter_socials[key] = value
                            # check: if 'key' is 'Twitter', 'facebook', 'linkedin'; as a recruiter needs only these.
                            elif key in ['twitter', 'facebook', 'linkedin']:
                                recruiter_socials[key] = value
                            # if the 'key' is not present, but it is one of these, 'twitter', 'facebook', 'linkedin'
                            elif key not in recruiter_socials and key in ['twitter', 'facebook', 'linkedin']:
                                recruiter_socials[key] = value
                            else:
                                print("---log-3---")
                                ...
                            recruiter_profile.save()
                    # check: if techie socials is not empty and recruiter's socials is (null) None.
                    elif techie_socials is not None and recruiter_socials is None:
                        # operation: get socials from techie if present.
                        recruiter_profile.socials = dict()
                        for key, value in techie_socials.items():
                            if key in ['twitter', 'linkedin', 'facebook']:
                                recruiter_profile.socials[key] = value
                            recruiter_profile.save()
                else:
                    # Since recruiter was not found, then create and transfer details to it.
                    recruiter_profile = RecruiterProfile.objects.create(user=request.user,
                                                                        owner_user_id=request.user.id)
                    # operation: get socials from techie if present.
                    techie_instance = TechieProfile.objects.get(user=user)
                    techie_instance.socials = dict()
                    techie_socials = techie_instance.socials
                    recruiter_profile.socials = dict()

                    for key, value in techie_socials.items():
                        if key in ['twitter', 'linkedin', 'facebook']:
                            recruiter_profile.socials[key] = value
                        recruiter_profile.save()
                serialized = RecruiterProfileSerializer(recruiter_profile, many=False,
                                                        context={"request": request}).data

                return Response({"detail": "You have switched to your Recruiter Profile",
                                 "data": serialized}, status=HTTP_200_OK)

            if request.user.user_role == "recruiter":
                user.user_role = "techie"
                user.save()

                techie_instance = None
                if TechieProfile.objects.filter(user=request.user).exists():
                    # Get his/her Techie's profile to collect switchable data like, socials,
                    techie_instance = TechieProfile.objects.get(user=user)
                    techie_socials = techie_instance.socials

                    recruiter_profile = RecruiterProfile.objects.get(user=request.user)
                    recruiter_socials = recruiter_profile.socials

                    if recruiter_socials is not None and techie_socials is not None:
                        if "" in techie_socials:
                            del techie_socials[""]

                        for key, value in recruiter_socials.items():
                            # check: if 'key' e.g 'facebook' in "recruiter's" socials and if "key's" value is not empty.
                            if key in techie_socials and bool(techie_socials[key]) is False:
                                techie_socials[key] = value
                            # check: if 'key' is 'Twitter', 'facebook', 'linkedin'; as a recruiter needs only these.
                            elif key in ['twitter', 'facebook', 'linkedin']:
                                techie_socials[key] = value
                            # if the 'key' is not present, but it is one of these, 'twitter', 'facebook', 'linkedin'
                            elif key not in techie_socials and key in ['twitter', 'facebook', 'linkedin']:
                                techie_socials[key] = value
                            else:
                                print("---log-3---")
                                ...
                            techie_instance.save()
                    elif recruiter_socials is not None and techie_socials is None:

                        techie_instance.socials = dict()
                        for key, value in recruiter_socials:
                            if key in ['twitter', 'linkedin', 'facebook']:
                                techie_instance.socials[key] = value
                            techie_instance.save()

                serialized = TechieProfileSerializer(techie_instance, many=False, context={"request": request}).data
                return Response({"detail": "You have switched to your Techie Profile", "data": serialized},
                                status=HTTP_200_OK)

            return Response({"detail": "Invalid user role type"}, status=HTTP_400_BAD_REQUEST)
        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)


class GenerateRandomActivationTokenView(APIView):
    permission_classes = []

    def post(self, request):
        try:
            """
                Make sure anybody visiting this endpoint is not a 'recruiter or a techie.
                Future feature for this endpoint:
                    - Will Un-verify 'techie' or 'recruiter' profile that visits this endpoint.
            """
            if request.user.is_anonymous:
                token = secrets.token_urlsafe(10)
                token_instance = ActivationToken.objects.create(token=token)
                return Response({"detail": f"{token_instance.token}"}, status=HTTP_201_CREATED)

            if request.user.user_role in ['recruiter', 'techie']:
                return Response({"detail": "You are not welcome here."}, status=status.HTTP_403_FORBIDDEN)

        except (Exception,) as err:
            return Response({"detail": str(err)}, status=HTTP_400_BAD_REQUEST)


class TokenVerificationView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, token):
        try:
            if not token:
                return Response({"detail": "Token is required"}, status=status.HTTP_400_BAD_REQUEST)

            if not (request.user.user_role in ['recruiter', 'techie'] and request.user.is_authenticated):
                return Response({"detail": "You are not Authenticated neither are you authenticated"},
                                status=status.HTTP_400_BAD_REQUEST)

            elif request.user.user_role == 'recruiter':
                print(request.user, "1")

            elif request.user.user_role == 'techie':
                print(request.user, '2')
            return Response({"detail": str("err")}, status=HTTP_400_BAD_REQUEST)

        except (Exception,) as err:
            return Response({"detail": str(err)}, status=HTTP_400_BAD_REQUEST)


class GetAllVerifiedCompanyView(APIView):
    permission_classes = []

    def get(self, request, pk=None):
        try:
            if pk:
                company = Company.objects.get(id=pk, verified=True, is_completed=True)
                serialized_data = CompanySerializer(company, context={"request": request}).data
                return Response({"detail": serialized_data})

            query_set = Company.objects.filter(verified=True, is_completed=True)
            serialized_data = CompanySerializer(query_set, many=True, context={"request": request}).data
            return Response({"detail": serialized_data})
        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=status.HTTP_400_BAD_REQUEST)


class UploadImageView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            user_image, user = request.data.get('user_image', None), request.user
            company_image = request.data.get('company_image', None)
            company_slug_or_id = request.data.get('company_slug_or_id', None)

            if 'user_image' in request.data and 'company_image' in request.data:
                return Response({"detail": f"This endpoint receives either 'user_image' or 'company_image' field per "
                                           f"request."}, status=status.HTTP_400_BAD_REQUEST)
            if "user_image" in request.data:
                success, msg = validate_image(image=user_image)
                if success:

                    user.image = user_image
                    user.save()
                    return Response({"detail": f"Successfully uploaded your image."})
                return Response({"detail": f"{msg}"}, status=status.HTTP_400_BAD_REQUEST)

            if "company_image" in request.data:
                if not company_image:
                    return Response({"detail": f"Company's image is required"}, status=status.HTTP_400_BAD_REQUEST)

                if company_slug_or_id is None:
                    return Response({"detail": f"The company's ID or Slug is required for image upload."},
                                    status=status.HTTP_400_BAD_REQUEST)

                # Check if user belongs to OR is creator of that company.
                if str(company_slug_or_id).isnumeric():
                    company = Company.objects.filter(id=company_slug_or_id)
                else:
                    company = Company.objects.filter(slug=company_slug_or_id)

                if not company:
                    return Response({"detail": f"Company with '{company_slug_or_id}' does not exists."},
                                    status=status.HTTP_404_NOT_FOUND)

                company = company.last()
                # Check if the current logged-in user is part of the creator of this Company.
                if company.creator.filter(user=request.user).exists():

                    # Run image check
                    success, msg = validate_image(image=company_image)
                    if success:
                        company.image = company_image
                        company.save()
                        return Response({"detail": f"Successfully uploaded your image."})
                    return Response({"detail": f"{msg}"}, status=status.HTTP_400_BAD_REQUEST)

                else:
                    return Response({"detail": f"You are not authorized to edit this company's image."},
                                    status=status.HTTP_401_UNAUTHORIZED)

        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request):
        try:
            image_type, user = request.data.get('image_type', None), request.user
            company_slug_or_id = request.data.get('company_slug_or_id', None)

            # Company Image Delete
            if image_type == "user":
                user.image = "user.jpeg"
                user.save()
                return Response({"detail": f"Image has been deleted."})

            # Company Image Delete
            if image_type == 'company' and company_slug_or_id is None:
                return Response({"detail": "This endpoint receives either 'image_type' and 'company_slug_or_id' "
                                           "to delete a company's image."}, status=status.HTTP_400_BAD_REQUEST)
            elif image_type != 'company' and company_slug_or_id is not None:
                return Response({"detail": "Invalid 'image_type' value."}, status=status.HTTP_400_BAD_REQUEST)

            elif image_type == "company" and company_slug_or_id is not None:
                # Check if user belongs to OR is creator of that company.
                if str(company_slug_or_id).isnumeric():
                    company = Company.objects.filter(id=company_slug_or_id)
                else:
                    company = Company.objects.filter(slug=company_slug_or_id)

                if not company:
                    return Response({"detail": f"Company with '{company_slug_or_id}' does not exists."},
                                    status=status.HTTP_404_NOT_FOUND)

                company = company.last()

                # Check if the current logged-in user is part of the creator of this Company.
                if company.creator.filter(user=request.user).exists():

                    # Run image check
                    # supplying the default image name will replace the company image field with the string pass
                    # provided the string is a valid image that is found in the 'upload' folder.
                    company.image = "company.jpeg"
                    company.save()
                    return Response({"detail": f"Image has been deleted."})

                else:
                    return Response({"detail": f"You are not authorized to edit this company's image."},
                                    status=status.HTTP_401_UNAUTHORIZED)

        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=status.HTTP_400_BAD_REQUEST)


class ProfileTokenVerificationView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """
            Obtain verification token.
            T - Techie
            R - Recruiter
        """
        try:
            if request.user.user_role == "techie":
                techie = TechieProfile.objects.get(user=request.user)

                if techie.verified:
                    return Response({"detail": "Profile is already verified."}, status=HTTP_400_BAD_REQUEST)

                verification_token = f"{secrets.token_urlsafe(6)}-T"
                techie.verification_token = verification_token
                techie.save()
                return Response({"detail": verification_token})

            if request.user.user_role == "recruiter":
                recruiter = RecruiterProfile.objects.get(user=request.user)

                if recruiter.verified:
                    return Response({"detail": "Profile is already verified."}, status=HTTP_400_BAD_REQUEST)

                verification_token = f"{secrets.token_urlsafe(6)}-R"
                recruiter.verification_token = verification_token
                recruiter.save()
                return Response({"detail": verification_token})

            return Response({"detail": "Account has no user profile attached."}, status=HTTP_400_BAD_REQUEST)
        except (Exception, ) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)


    def put(self, request):
        try:
            u_token = request.data.get('token', None)

            if not u_token:
                return Response({"detail": f"Token is required."}, status=HTTP_400_BAD_REQUEST)

            if request.user.user_role == "techie":
                techie = TechieProfile.objects.get(user=request.user)
                if techie.verification_token == u_token:

                    # Check if profile is completed.
                    if not techie.is_completed:
                        techie.verified = False
                        techie.verification_token = ""
                        techie.save()
                        return Response({"detail": "Your techie profile is yet to be completed completed."}, status=HTTP_400_BAD_REQUEST)

                    techie.verified = True
                    techie.verification_token = ""
                    techie.save()
                    return Response({"detail": "You are now a verified Techie."})
                return Response({"detail": "Invalid Techie token."}, status=HTTP_400_BAD_REQUEST)

            if request.user.user_role == "recruiter":
                recruiter = RecruiterProfile.objects.get(user=request.user)
                if recruiter.verification_token == u_token:

                    # Check if profile is completed.
                    if not recruiter.is_completed:
                        recruiter.verified = False
                        recruiter.verification_token = ""
                        recruiter.save()
                        return Response({"detail": "Your recruiter profile is yet to be completed."}, status=HTTP_400_BAD_REQUEST)

                    recruiter.verified = True
                    recruiter.verification_token = ""
                    recruiter.save()
                    return Response({"detail": "You are now a verified Recruiter."})
                return Response({"detail": f"Invalid Recruiter token."}, status=HTTP_400_BAD_REQUEST)

            return Response({"detail": "Account has no user profile attached."}, status=HTTP_400_BAD_REQUEST)
        except (Exception, ) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)

class ChangePasswordView(APIView):
    permission_classes = [IsAuthenticated]

    def put(self, request):
        try:
            password = request.data.get("password", None)
            password_confirm1 = request.data.get("password_confirm1", None)
            password_confirm2 = request.data.get("password_confirm2", None)

            if not password:
                return Response({"detail": f"Password is required"}, status=HTTP_400_BAD_REQUEST)

            if not password_confirm1:
                return Response({"detail": f"Password confirm is required"}, status=HTTP_400_BAD_REQUEST)

            if not password_confirm2:
                return Response({"detail": f"Password is required"}, status=HTTP_400_BAD_REQUEST)

            if password_confirm2 != password_confirm1:
                return Response({"detail": f"Passwords does not match"}, status=HTTP_400_BAD_REQUEST)

            user = request.user

            if not check_password(password=password, encoded=user.password):
                return Response({"detail": "Incorrect old password"}, status=HTTP_400_BAD_REQUEST)

            user.password = make_password(password=password_confirm1)
            user.save()

            return Response({"detail": "Password has been successfully reset"})
        except (Exception, ) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)


class GeneralSearchView(APIView):
    permission_classes = []

    def get(self, request):
        try:
            query = request.data.get("query", None)

            if not query:
                return Response({"detail": f"'query' parameter is required"}, status=HTTP_400_BAD_REQUEST)
            # username, first_name, last_name, email, headline

            query = Q(first_name=query)

            query_set = User.objects.filter(username=query)
            if User.objects.filter(username=query):
                query  = None

            if User.objects.filter(username=query):
                query = None

            return Response({"detail": f""})
        except (Exception,) as err:
            return Response({"detail": f"{err}"}, status=HTTP_400_BAD_REQUEST)
